config/routes.rb
Rails.application.routes.draw do
  resources :maintenance_services
  resources :cars

  root 'cars#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # API routes
 namespace :api do
   namespace :v1 do
     resources :maintenance_services
     resources :cars
   end
 end

end

app/models/car.rb
class Car < ApplicationRecord
  validates_uniqueness_of :plate_number, message:'Estas placas ya fueron registradas con anterioridad' , allow_blank: false
  validates :year,
              numericality: {
                              only_integer: true,
                              greater_than_or_equal_to: 1900,
                              less_than_or_equal_to: Date.today.year,
                              message: "El año debe de ser entre 1900 y #{Date.today.year}"
                              }

 # inclusion: { in: 1900..Date.today.year },
  has_many :maintenance_services
end

app/controllers/api/v1/cars_controller.rb
module Api
  module V1
    class CarsController < ApplicationController
      skip_before_action :verify_authenticity_token

      def index
        @cars = Car.order('created_at DESC')
        render json: {status: 'SUCCESS', data:@cars}
      end

      def show
        @car = Car.find(params[:id])

        render json: {status: 'SUCCESS', data:@car}, status: :ok
      end

      def create
        @car = Car.new(car_params)

        if @car.save
          render json: {status: 'SUCCESS', data:@car}, status: :ok
        else
          render json: {status: 'Error', data:@car.errors}, status: :unprocessable_entity
        end
      end

      def update
        @car = Car.find(params[:id])

        if @car.update(car_params)
          render json: {status: 'SUCCESS', data:@car}, status: :ok
        else
          render json: {status: 'Error', data:@car.errors}, status: :unprocessable_entity
        end
      end

      def destroy
        @car = Car.find(params[:id])
        @car.destroy

        render json: {status: 'SUCCESS', data:@car}, status: :ok
      end

      private
        def car_params
          params.permit(:plate_number, :model, :year)
        end

    end
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]

  # GET /cars or /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1 or /cars/1.json
  def show

    @maintenance_service = MaintenanceService.new
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.maintenance_services.clear
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_path, status: :see_other, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:plate_number, :model, :year)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Placas' %>
    <%= form.text_field :plate_number %>
  </div>

  <div class="field">
    <%= form.label 'Modelo' %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label 'Año' %>
    <%= form.number_field :year %>
  </div>

  <div class="actions">
    <%= form.submit 'Gurdar', class: 'btn btn-success btn-sm' %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editar Carro</h1>

<%= render 'form', car: @car %>

<%= link_to 'Detalles', @car, class:'btn btn-warning btn-sm' %> |
<%= link_to 'Lista de carros', cars_path, class: 'btn btn-info btn-sm' %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de carros</h1>

<%= link_to 'Lista de mantenimiento', maintenance_services_path, class: 'btn btn-info btn-sm' %>
<%= link_to 'Nuevo Carro', new_car_path, class: 'btn btn-success btn-sm' %>
<table class="table" >
  <thead>
    <tr>
      <th>Placa</th>
      <th>Modelo</th>
      <th>Año</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.plate_number %></td>
        <td><%= car.model %></td>
        <td><%= car.year %></td>
        <td>
          <%if car.maintenance_services.length > 0 %>
            <button type="button" name="button" class="btn btn-info btn-sm" id="<%= car.id %>" onclick="openLogMaintenance(this)">Historial</button>
          <% end %>
        </td>
        <td><%= link_to car, :class=> "btn btn-warning btn-sm" do  %> Detalles<% end %></td>
        <td><%= link_to edit_car_path(car), :class=> "btn btn-info btn-sm" do  %> Editar<% end %></td>
        <td>
          <%= button_to car, method: :delete,:onclick => "return confirm('Esta seguro de eliminar el carro, esto tambien elminara los registro de mantenimiento?')" , :class=> "btn btn-danger btn-sm" do %>Eliminar<% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/cars/new.html.erb
<h1>Nuevo Carro</h1>

<%= render 'form', car: @car %>

<%= link_to 'Lista de carros', cars_path, class: 'btn btn-info btn-sm' %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row mb-4">
  <div class="col-md-3">
    <label for="">Placas</label>
    <%= @car.plate_number %>
  </div>
  <div class="col-md-3">
    <label>Model:</label>
    <%= @car.model %>
  </div>
  <div class="col-md-3">
    <label>Year:</label>
    <%= @car.year %>
  </div>
  <div class="col-md-3">
    <button type="button" name="button" class="btn btn-success btn-sm" onclick="openModalNMS()">Nuevo Servicio</button>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Descripción</th>
      <th>Status</th>
      <th>Fecha servicio</th>
    </tr>
  </thead>
  <tbody>

    <%@car.maintenance_services.each do |m| %>
      <tr>
        <td><%= m.description%></td>
        <td><%= m.status%></td>
        <td><%= m.date%></td>
      </tr>
    <%end%>
  </tbody>
</table>
<%= link_to 'Editar', edit_car_path(@car), class:'btn btn-warning btn-sm' %> |
<%= link_to 'Lista de carros', cars_path, class: 'btn btn-info btn-sm' %>


<div class="modal" id="modal_new_ms" tabindex="-1" aria-labelledby="modal_custom" aria-hidden="true" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog  modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header" id="head_ms">
        <h5><%= @car.plate_number %></h5>
      </div>
      <div class="modal-body" id="body_ms">
        <%= form_for(@maintenance_service, :html => {:id => 'new_cmaintenance_service'}) do |form| %>

          <div class="field">
            <input type="hidden" name="maintenance_service[car_id]" id="maintenance_service_id" value="<%= @car.id %>">
            <%= form.label :description %>
            <%= form.text_field :description %>
          </div>

          <div class="field">
            <%= form.label :status %>
            <%= form.text_field :status %>
          </div>

        <% end %>
      </div>
      <div class="modal-footer" id="ftr_ms">
        <button type="button" class="btn btn-danger btn-sm" onclick="closeModalMS(this)">Close</button>
        <button type="button" name="button" class="btn btn-success btn-sm" onclick="saveData(this)">Crear servicio</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  function openModalNMS(){
    $('#modal_new_ms').toggle()
  }

 function closeModalMS(){
   $('#modal_new_ms').toggle()
 }

 function saveData(event){
   const form_d = $('#new_cmaintenance_service').serialize()
   $.ajax({
     beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
     url: "/maintenance_services.json",
     type: "post",
     data: form_d,
     dataType: 'JSON',
     success: function(data) {
       location.reload();
     },
     error: function(data,t,d){
       $('#notice').text(data.responseJSON.description[0])
     }
   });
  }
 </script>