config/routes.rb
Rails.application.routes.draw do
  resources :maintenance_services
  resources :cars

  root 'cars#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # API routes
 namespace :api do
   namespace :v1 do
     resources :maintenance_services
     resources :cars
   end
 end

end

app/models/maintenance_service.rb
class MaintenanceService < ApplicationRecord
  validates_uniqueness_of :description, presence: true, allow_blank: false, message: "Favor de ingresar una descripción"
  enum status: { pending: 0, in_progress: 1, completed: 2 }
  belongs_to :car

   before_create :default_values

   def default_values
     self.date = Date.today
   end

   def self.filter_services(plate_number, status)

     _where_plate_number = ''
     _where_status = '0=0'

     if !plate_number.blank?
       list_car = Car.select(:id).where("plate_number like '%#{plate_number}%'")
       map_car = list_car.map{ |key| key.id }.join(', ')
       _where_plate_number = " and car_id in (#{map_car})"
     end

     if !status.blank?
       _where_status = " status = #{status} "
     end

     ms = MaintenanceService.where("#{_where_status} #{_where_plate_number}")

     ms

   end
end

app/controllers/api/v1/maintenance_services_controller.rb
module Api
  module V1
    class MaintenanceServicesController < ApplicationController
      skip_before_action :verify_authenticity_token

      def index
        @maintenance_services = MaintenanceService.order('created_at DESC')
        render json: {status: 'SUCCESS', data:@maintenance_services}, status: :ok
      end

      def show
        @maintenance_service = MaintenanceService.find(params[:id])
        render json: {status: 'SUCCESS', data:@maintenance_service}, status: :ok
      end

      def create
        @maintenance_service = MaintenanceService.new(maintenance_service_params)

        if @maintenance_service.save
          render json: {status: 'SUCCESS', data:@maintenance_service, message:'Servicio creado correctamente'}, status: :ok
        else
          render json: {status: 'Error', data:@maintenance_service.errors}, status: :unprocessable_entity
        end
      end

      def update
        @maintenance_service = MaintenanceService.find(params[:id])

        if @maintenance_service.update(maintenance_service_params)
          render json: {status: 'SUCCESS', data:@maintenance_service}, status: :ok
        else
          render json: {status: 'Error', data:@maintenance_service.errors}, status: :unprocessable_entity
        end
      end

      def destroy
        @maintenance_service = MaintenanceService.find(params[:id])
        @maintenance_service.destroy

        render json: {status: 'SUCCESS', data:@maintenance_service}, status: :ok
      end

      private
        def maintenance_service_params
          params.permit(:car_id, :description, :status, :date)
        end

    end
  end
end

app/controllers/maintenance_services_controller.rb
class MaintenanceServicesController < ApplicationController
  before_action :set_maintenance_service, only: %i[ show edit update destroy ]

  # GET /maintenance_services or /maintenance_services.json
  def index
    @search_plate_number = ''
    @status = ''
    @search_plate_number = params[:search_plate_number] if params[:search_plate_number]
    @status = params[:status] if params[:status]

    @maintenance_services = MaintenanceService.filter_services(@search_plate_number, @status)
  end

  # GET /maintenance_services/1 or /maintenance_services/1.json
  def show
  end

  # GET /maintenance_services/new
  def new
    @maintenance_service = MaintenanceService.new
  end

  # GET /maintenance_services/1/edit
  def edit
  end

  # POST /maintenance_services or /maintenance_services.json
  def create
    @maintenance_service = MaintenanceService.new(maintenance_service_params)

    respond_to do |format|
      if @maintenance_service.save
        format.html { redirect_to @maintenance_service, notice: "El servicio fue creado correctamente." }
        format.json { render :show, status: :created, location: @maintenance_service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @maintenance_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maintenance_services/1 or /maintenance_services/1.json
  def update
    respond_to do |format|
      if @maintenance_service.update(maintenance_service_params)
        format.html { redirect_to @maintenance_service, notice: "El servicio fue actualizado correctamente." }
        format.json { render :show, status: :ok, location: @maintenance_service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @maintenance_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maintenance_services/1 or /maintenance_services/1.json
  def destroy
    @maintenance_service.destroy

    respond_to do |format|
      format.html { redirect_to maintenance_services_path, status: :see_other, notice: "El servicio fue eliminado correctamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maintenance_service
      @maintenance_service = MaintenanceService.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def maintenance_service_params
      params.require(:maintenance_service).permit(:car_id, :description, :status, :date)
    end
end

app/helpers/maintenance_services_helper.rb
module MaintenanceServicesHelper
end

app/views/maintenance_services/_form.html.erb
<%= form_with(model: maintenance_service) do |form| %>
  <% if maintenance_service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(maintenance_service.errors.count, "error") %> prohibited this maintenance_service from being saved:</h2>

      <ul>
        <% maintenance_service.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <%= form.hidden_field :car_id %>


  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :status %>

    <%= form.select :status, options_for_select([['pending', 0], ['in_progress', 1], ['completed', 2]]), :class => 'form-control' %>
  </div>


  <div class="actions">
    <%= form.submit 'Gurdar', class: 'btn btn-success btn-sm' %>
  </div>
<% end %>

app/views/maintenance_services/edit.html.erb
<h1>Editar registro del servicio</h1>

<%= render 'form', maintenance_service: @maintenance_service %>

<%= link_to 'Detalles', @maintenance_service, class:'btn btn-warning btn-sm' %> |
<%= link_to 'Tablero de Mantenimiento', maintenance_services_path, class: 'btn btn-info btn-sm' %>

app/views/maintenance_services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tablero de Mantenimiento</h1>
<%= form_tag maintenance_services_path, :method => 'get' do %>
  <div class="card mb-4">
    <div class="card-body">
      <div class="row">
        <div class="col-md-2">
          <input  class="form-control" type="text" name="search_plate_number" value="<%= @search_plate_number %>" placeholder="placas">
        </div>
        <div class="col-md-2">
           <%= select_tag :status, options_for_select([['pending', 0], ['in_progress', 1], ['completed', 2]], params[:status]), {:prompt => 'Selecione una status', class: 'form-control'} %>
        </div>
        <div class="col-md-2">
            <%= submit_tag "Buscar", :name => nil, class: 'btn btn-success btn-sm' %>
            <%= link_to 'Lista de carros', cars_path, class: 'btn btn-info btn-sm' %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<table class="table">
  <thead class="table-light">
    <tr>
      <th>Placas</th>
      <th>Descripción</th>
      <th>Status</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maintenance_services.each do |maintenance_service| %>
      <tr>
        <td><%= maintenance_service.car.plate_number %></td>
        <td><%= maintenance_service.description %></td>
        <td><%= maintenance_service.status %></td>
        <td><%= maintenance_service.date %></td>
        <td><%= link_to maintenance_service, :class=> "btn btn-warning btn-sm" do  %> Detalles<% end %></td>
        <td><%= link_to edit_maintenance_service_path(maintenance_service), :class=> "btn btn-info btn-sm" do  %> Editar<% end %></td>
        <td>
          <%= button_to maintenance_service, method: :delete,:onclick => "return confirm('Esta seguro de eliminar el registro?')" , :class=> "btn btn-danger btn-sm" do %>Eliminar<% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/maintenance_services/new.html.erb
<h1>New Maintenance Service</h1>

<%= render 'form', maintenance_service: @maintenance_service %>
 

<%= link_to 'Back', maintenance_services_path %>

app/views/maintenance_services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Car:</strong>
  <%= @maintenance_service.car_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @maintenance_service.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @maintenance_service.status %>
</p>

<p>
  <strong>Date:</strong>
  <%= @maintenance_service.date %>
</p>

<%= link_to 'Editar', edit_maintenance_service_path(@maintenance_service), class:'btn btn-warning btn-sm' %> |
<%= link_to 'Tablero de Mantenimiento', maintenance_services_path, class: 'btn btn-info btn-sm' %>